const PRODUCTOS_RESPALDO = [
  {
    id: 1,
    nombre: "Mochila Fjallraven Foldsack No.1",
    title: "Mochila Fjallraven Foldsack No.1",
    precio: 109.95,
    price: 109.95,
    descripcion: "Mochila perfecta para el uso diario o caminatas al aire libre. Cuenta con compartimiento acolchado para laptop de 15 pulgadas.",
    description: "Mochila perfecta para el uso diario o caminatas al aire libre. Cuenta con compartimiento acolchado para laptop de 15 pulgadas.",
    categoria: "men's clothing",
    category: "men's clothing",
    imagen: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    valoracion: 3.9,
    rating: 3.9
  },
  {
    id: 2,
    nombre: "Camiseta de Ajuste Slim Fit para Hombre",
    title: "Camiseta de Ajuste Slim Fit para Hombre",
    precio: 22.3,
    price: 22.3,
    descripcion: "Camiseta deportiva casual premium de corte ajustado, ligera y transpirable para cualquier tipo de actividad física.",
    description: "Camiseta deportiva casual premium de corte ajustado, ligera y transpirable para cualquier tipo de actividad física.",
    categoria: "men's clothing",
    category: "men's clothing",
    imagen: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    image: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    valoracion: 4.1,
    rating: 4.1
  },
  {
    id: 3,
    nombre: "Chaqueta de Algodón Casual de Hombre",
    title: "Chaqueta de Algodón Casual de Hombre",
    precio: 55.99,
    price: 55.99,
    descripcion: "Excelente chaqueta de algodón abrigadora para climas fríos o salidas nocturnas casuales. Diseño moderno de múltiples bolsillos.",
    description: "Excelente chaqueta de algodón abrigadora para climas fríos o salidas nocturnas casuales. Diseño moderno de múltiples bolsillos.",
    categoria: "men's clothing",
    category: "men's clothing",
    imagen: "https://fakestoreapi.com/img/71li-alajOL._AC_UX679_.jpg",
    image: "https://fakestoreapi.com/img/71li-alajOL._AC_UX679_.jpg",
    valoracion: 4.7,
    rating: 4.7
  },
  {
    id: 4,
    nombre: "Anillo Solitario de Oro Blanco 14k",
    title: "Anillo Solitario de Oro Blanco 14k",
    precio: 9500,
    price: 9500,
    descripcion: "Hermoso anillo solitario clásico para compromiso con diamante de corte brillante. Diseñado en oro blanco genuino de 14 quilates.",
    description: "Hermoso anillo solitario clásico para compromiso con diamante de corte brillante. Diseñado en oro blanco genuino de 14 quilates.",
    categoria: "jewelery",
    category: "jewelery",
    imagen: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    valoracion: 4.6,
    rating: 4.6
  },
  {
    id: 5,
    nombre: "Disco Duro Externo Portable de 1TB",
    title: "Disco Duro Externo Portable de 1TB",
    precio: 64.0,
    price: 64.0,
    descripcion: "Disco duro externo USB 3.0 para copias de seguridad de datos ultrarrápidas, compatible con PC, Mac, Xbox y PlayStation.",
    description: "Disco duro externo USB 3.0 para copias de seguridad de datos ultrarrápidas, compatible con PC, Mac, Xbox y PlayStation.",
    categoria: "electronics",
    category: "electronics",
    imagen: "https://fakestoreapi.com/img/61IBJVJIGmL._AC_SL1500_.jpg",
    image: "https://fakestoreapi.com/img/61IBJVJIGmL._AC_SL1500_.jpg",
    valoracion: 3.3,
    rating: 3.3
  },
  {
    id: 6,
    nombre: "Chaqueta Impermeable Rain Jacket para Mujer",
    title: "Chaqueta Impermeable Rain Jacket para Mujer",
    precio: 39.99,
    price: 39.99,
    descripcion: "Chaqueta rompevientos impermeable ligera para dama, ideal para escalar, acampar, correr y deportes al aire libre.",
    description: "Chaqueta rompevientos impermeable ligera para dama, ideal para escalar, acampar, correr y deportes al aire libre.",
    categoria: "women's clothing",
    category: "women's clothing",
    imagen: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-1.jpg",
    image: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-1.jpg",
    valoracion: 3.8,
    rating: 3.8
  }
];
window.PRODUCTOS_RESPALDO = PRODUCTOS_RESPALDO;
